// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHHnRKDAFr3yQzf7Hnm27ceIoF2UHj3I',
    appId: '1:486509842743:web:650a96a42cbf5998490ab2',
    messagingSenderId: '486509842743',
    projectId: 'copa-palpite',
    authDomain: 'copa-palpite.firebaseapp.com',
    databaseURL: 'https://copa-palpite-default-rtdb.firebaseio.com',
    storageBucket: 'copa-palpite.firebasestorage.app',
    measurementId: 'G-527LK0S5T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-D19dn_Sb0UW2KQXcGNPLznW8jZlttUI',
    appId: '1:486509842743:android:9a0e1677a1c8367f490ab2',
    messagingSenderId: '486509842743',
    projectId: 'copa-palpite',
    databaseURL: 'https://copa-palpite-default-rtdb.firebaseio.com',
    storageBucket: 'copa-palpite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydZEAatgdEZv7CZiHVkJ73MNTfITjGsg',
    appId: '1:486509842743:ios:73d36818527f9ac6490ab2',
    messagingSenderId: '486509842743',
    projectId: 'copa-palpite',
    databaseURL: 'https://copa-palpite-default-rtdb.firebaseio.com',
    storageBucket: 'copa-palpite.firebasestorage.app',
    androidClientId:
        '486509842743-isocuh93mki305jf7ne9sotm4ib5c9ol.apps.googleusercontent.com',
    iosClientId:
        '486509842743-1bsb06e0fbe9i1hsijmumfia0648cl2d.apps.googleusercontent.com',
    iosBundleId: 'com.copapalpite.app',
  );
}
